# Generated by Django 6.0.6 on 2026-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropprice',
            name='altitude_m',
            field=models.IntegerField(default=1600),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='export_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='variety_type',
            field=models.CharField(default='arabica', max_length=20),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='emoji',
            field=models.CharField(default='☕', max_length=10),
        ),
    ]
