# Generated by Django 6.0.6 on 2026-06-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_cropprice_altitude_m_cropprice_export_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropprice',
            name='altitude_m',
        ),
        migrations.RemoveField(
            model_name='cropprice',
            name='district',
        ),
        migrations.RemoveField(
            model_name='cropprice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cropprice',
            name='province',
        ),
        migrations.AddField(
            model_name='cropprice',
            name='cooperative_rwf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='farmgate_rwf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='season',
            field=models.CharField(choices=[('Season A', 'Season A — Main Harvest'), ('Season B', 'Season B — Fly Crop'), ('Off Season', 'Off Season')], default='Off Season', max_length=20),
        ),
        migrations.AddField(
            model_name='cropprice',
            name='trend_label',
            field=models.CharField(default='Stable Market →', max_length=30),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='emoji',
            field=models.CharField(default='☕', max_length=20),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='trend',
            field=models.CharField(choices=[('rising', 'Rising Market'), ('stable', 'Stable Market'), ('falling', 'Falling Market')], default='stable', max_length=10),
        ),
    ]
