# Generated by Django 6.0.6 on 2026-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='emoji',
            field=models.CharField(default='☕', max_length=20),
        ),
    ]
